- id: pmid:35452090
  title: The archaeal glutamate transporter homologue GltPh shows heterogeneous substrate
    binding.
  authors:
  - "**Krishna D Reddy**"#
  - Didar Ciftci
  - Amanda J Scopelliti
  - Olga Boudker#
  publisher: The Journal of general physiology
  date: '2022-04-22'
  link: https://www.ncbi.nlm.nih.gov/pubmed/35452090
  orcid: 0000-0002-0475-8375
